id: AAF475BF4
base_file: fCB5B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:03:56.719173
  last_modified_at: 2022-05-30 23:03:56.719179
