id: AAF475BF4
base_file: f5115.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:03:56.713644
  last_modified_at: 2022-05-30 23:03:56.713650
