id: AAF475BF4
base_file: f5E57.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:03:56.716839
  last_modified_at: 2022-05-30 23:03:56.716880
